### ISSUE TITLE
[Help] VRAM required for model inference and enable multiple GPUs

### ISSUE THREAD

**Issue by Mingzefei** [potamides/AutomaTikZ#10]
Wonderful job! I would love to deploy it locally with two 4090 GPUs, each with 24GB of VRAM, but I keep getting a 'cuda out of memory' error when loading clima-13b. 
Therefore, I have two questions:
1. How much VRAM is required for each model's inference?
2. How can I correctly set up and enable multiple GPUs?

**Comment by potamides** [comment]
Thanks!

>How much VRAM is required for each model's inference?

24GB is enough for 7b model inference, but for the 13b model you'd need to split it across your two GPUs (see below how to do that).

>How can I correctly set up and enable multiple GPUs?

If you are asking about inference, try adding `device_map="auto"` to your load arguments, as is done for the
webui [here](https://github.com/potamides/AutomaTikZ/blob/79e89dddb7e8edce4290d5335fc0888b1a95a2d3/examples/webui/webui.py#L46). This should split your model across your two GPUs.

**Comment by Mingzefei** [comment]
Thank you for the comment!
It is running normally now.
