### ISSUE TITLE
【Question】Is there a docker image that can run this project?

### ISSUE THREAD

**Issue by JSHZT** [potamides/AutomaTikZ#17]
Is there a docker image that can run this project?
 "AutomaTikZ additionally requires a full TeX Live installation, ghostscript, and, for rasterization of vector graphics, poppler." 
 This installation is tedious and error-prone.

**Comment by potamides** [comment]
We don't provide an official docker image at the moment, but we use the following [Dockerfile](https://huggingface.co/spaces/nllg/AutomaTikZ/blob/main/Dockerfile) to build our HF Space. Does that help?

**Comment by JSHZT** [comment]
thank you very much
