### ISSUE TITLE
Unable to install text2tikz package

### ISSUE THREAD

**Issue by sanjayss34** [potamides/AutomaTikZ#2]
Thanks for releasing your work. When I try to load the dataset, I get a message saying "To be able to use datikz, you need to install the following dependencies: fitz, pdf2image, pdfCropMargins, llm, text2tikz. Please install them using 'pip install fitz pdf2image pdfCropMargins llm text2tikz' for instance'"

However, `pip install text2tikz` tlls me that there is no such package available. Can you please advise on how to acquire the dataset? It would be very helpful if you are able to directly release the data files without us having to load the dataset via the script. Thanks again!

**Comment by potamides** [comment]
Thanks for reporting this bug! It should work now.
